#  音源
path:
  # 音声データのディレクトリ名
  sound_dir_name: "VCTK"
  # 雑音のディレクトリ名 / ファイル名
  noise_dir_name: "DEMAND"
  # 出力先のディレクトリ名
  output_dir_name: "VCTK_DEMAND_4ch_linear_10cm_1000cm_1000cm_1000cm"
  # 処理する音声の種類
  wave_type_list: ["train", "val", "test"]

# 部屋の条件
room:
  # シミュレーションのパラメータを保存しているディレクトリ (precompute_paramsの出力ディレクトリ名)
  # ディレクトリ内に部屋のパラメータ(JSON)が複数ある場合，ランダムで選択する
  # 単一のjsonファイルのみ(指定する部屋が1つ)の音声を作成したい場合，はprecompute_parmsの出力ディレクトリ以降のファイルパスパスを指定
  precomputed_path: "precomputed_params_2/1000cm_1000cm_1000cm.json"
  # SNR (最小値，最大値，ステップ)
  snr: [-5, 10, 1]
  # 残響時間 (最小値，最大値)
  rt60: [0.3, 1.0]

# マイクの条件
mic:
  # チャンネル数
  channel: 4
  # アレイマイクの中心点
  position_strategy: 'center' # 部屋の中心
  # channelが1のとき，以下の設定は無視される
  # アレイの形状 (linear / circular)
  array_type: "linear"
  # マイクの間隔 (cm)
  distance: 10
  # マイクの直径 (cm)
  diameter: 10


# 音源の条件
source:
  # 音声
  speech:
    # 水平角 (度) 90度がマイクの正面
    horizon: 90
    # 仰角 (度) 0度がマイクの正面
    elevate: 0
    # 距離 (m) アレイマイクの中心点からの距離
    distance: 0.3
  # 雑音
  noise:
    # 水平角 (度) 0度がマイクの右側
    horizon: 0
    # 仰角 (度) 0度がマイクの正面
    elevate: 0
    # 距離 (m) アレイマイクの中心点からの距離
    distance: 0.7